apiVersion: apps/v1
kind: Deployment
metadata:
  name: startservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startservice
  template:
    metadata:
      labels:
        app: startservice
    spec:
      containers:
        - name: startservice
          image: cynus2810/startservice:latest
          