apiVersion: v1
kind: Service
metadata:
  name: startservice-srv
spec:
  type: NodePort
  selector:
    app: startservice
  ports:
    - name: startservice
      protocol: TCP
      port: 80
      targetPort: 80